# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!
  PRODUCT_CMD: cmd/product
  WAREHOUSE_CMD: cmd/graph
  PROTO_DIR: api
  PROTO_GEN_FILE: pkg
  CURRENT_DATE:
    sh: bash -c 'date "+%Y-%m-%d %H:%M:%S"'
  OUTPUT: bin

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  product_build:
    desc: Build product app
    cmds:
      - |
        go build \
        -o {{.OUTPUT}}/graph \
        ./{{.WAREHOUSE_CMD}}

  warehouse_build:
    desc: Build graph app
    cmds:
      - |
        go build \
        -o {{.OUTPUT}}/product \
        ./{{.PRODUCT_CMD}}

  common_proto_gen_v1:
    desc: Generate common schemas
    cmds:
      - |
        protoc \
          --go_out={{.PROTO_GEN_FILE}}\
          --go_opt=paths=source_relative \
          --go-grpc_out={{.PROTO_GEN_FILE}} \
          --go-grpc_opt=paths=source_relative \
          {{.PROTO_DIR}}/common/v1/errors.proto
  product_proto_gen_v1:
    desc: Generate product schemas
    cmds:
      - |
        protoc \
          --go_out={{.PROTO_GEN_FILE}}\
          --go_opt=paths=source_relative \
          --go-grpc_out={{.PROTO_GEN_FILE}} \
          --go-grpc_opt=paths=source_relative \
          {{.PROTO_DIR}}/products/v1/specification.proto

  warehouse_proto_gen_v1:
    desc: Generate warehouses schemas
    cmds:
      - |
        protoc \
          --go_out={{.PROTO_GEN_FILE}} \
          --go_opt=paths=source_relative \
          --go-grpc_out={{.PROTO_GEN_FILE}} \
          --go-grpc_opt=paths=source_relative \
          {{.PROTO_DIR}}/warehouses/v1/warehouse.proto