// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/errors.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationError struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message     *string                `protobuf:"bytes,1,opt,name=message"`
	xxx_hidden_Members     []string               `protobuf:"bytes,2,rep,name=members"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_api_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_api_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ValidationError) GetMembers() []string {
	if x != nil {
		return x.xxx_hidden_Members
	}
	return nil
}

func (x *ValidationError) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ValidationError) SetMembers(v []string) {
	x.xxx_hidden_Members = v
}

func (x *ValidationError) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ValidationError) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Message = nil
}

type ValidationError_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Message *string
	Members []string
}

func (b0 ValidationError_builder) Build() *ValidationError {
	m0 := &ValidationError{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Message = b.Message
	}
	x.xxx_hidden_Members = b.Members
	return m0
}

type EntityError struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EntityName  *string                `protobuf:"bytes,1,opt,name=entity_name,json=entityName"`
	xxx_hidden_Id          *string                `protobuf:"bytes,2,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EntityError) Reset() {
	*x = EntityError{}
	mi := &file_api_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityError) ProtoMessage() {}

func (x *EntityError) ProtoReflect() protoreflect.Message {
	mi := &file_api_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EntityError) GetEntityName() string {
	if x != nil {
		if x.xxx_hidden_EntityName != nil {
			return *x.xxx_hidden_EntityName
		}
		return ""
	}
	return ""
}

func (x *EntityError) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *EntityError) SetEntityName(v string) {
	x.xxx_hidden_EntityName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *EntityError) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *EntityError) HasEntityName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EntityError) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EntityError) ClearEntityName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EntityName = nil
}

func (x *EntityError) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Id = nil
}

type EntityError_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EntityName *string
	Id         *string
}

func (b0 EntityError_builder) Build() *EntityError {
	m0 := &EntityError{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EntityName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_EntityName = b.EntityName
	}
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type ErrorDetail struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Code             int32                  `protobuf:"varint,1,opt,name=code"`
	xxx_hidden_Message          *string                `protobuf:"bytes,2,opt,name=message"`
	xxx_hidden_ValidationErrors *[]*ValidationError    `protobuf:"bytes,3,rep,name=validation_errors,json=validationErrors"`
	xxx_hidden_EntityErrors     *[]*EntityError        `protobuf:"bytes,4,rep,name=entity_errors,json=entityErrors"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_api_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ErrorDetail) GetCode() int32 {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return 0
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ErrorDetail) GetValidationErrors() []*ValidationError {
	if x != nil {
		if x.xxx_hidden_ValidationErrors != nil {
			return *x.xxx_hidden_ValidationErrors
		}
	}
	return nil
}

func (x *ErrorDetail) GetEntityErrors() []*EntityError {
	if x != nil {
		if x.xxx_hidden_EntityErrors != nil {
			return *x.xxx_hidden_EntityErrors
		}
	}
	return nil
}

func (x *ErrorDetail) SetCode(v int32) {
	x.xxx_hidden_Code = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ErrorDetail) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ErrorDetail) SetValidationErrors(v []*ValidationError) {
	x.xxx_hidden_ValidationErrors = &v
}

func (x *ErrorDetail) SetEntityErrors(v []*EntityError) {
	x.xxx_hidden_EntityErrors = &v
}

func (x *ErrorDetail) HasCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ErrorDetail) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ErrorDetail) ClearCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Code = 0
}

func (x *ErrorDetail) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type ErrorDetail_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Code             *int32
	Message          *string
	ValidationErrors []*ValidationError
	EntityErrors     []*EntityError
}

func (b0 ErrorDetail_builder) Build() *ErrorDetail {
	m0 := &ErrorDetail{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Code != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Code = *b.Code
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Message = b.Message
	}
	x.xxx_hidden_ValidationErrors = &b.ValidationErrors
	x.xxx_hidden_EntityErrors = &b.EntityErrors
	return m0
}

var File_api_errors_proto protoreflect.FileDescriptor

const file_api_errors_proto_rawDesc = "" +
	"\n" +
	"\x10api/errors.proto\x12\x06errors\x1a!google/protobuf/go_features.proto\"E\n" +
	"\x0fValidationError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\">\n" +
	"\vEntityError\x12\x1f\n" +
	"\ventity_name\x18\x01 \x01(\tR\n" +
	"entityName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xbb\x01\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\x11validation_errors\x18\x03 \x03(\v2\x17.errors.ValidationErrorR\x10validationErrors\x128\n" +
	"\rentity_errors\x18\x04 \x03(\v2\x13.errors.EntityErrorR\fentityErrorsB\x10Z\x06/proto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_api_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_errors_proto_goTypes = []any{
	(*ValidationError)(nil), // 0: errors.ValidationError
	(*EntityError)(nil),     // 1: errors.EntityError
	(*ErrorDetail)(nil),     // 2: errors.ErrorDetail
}
var file_api_errors_proto_depIdxs = []int32{
	0, // 0: errors.ErrorDetail.validation_errors:type_name -> errors.ValidationError
	1, // 1: errors.ErrorDetail.entity_errors:type_name -> errors.EntityError
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_errors_proto_init() }
func file_api_errors_proto_init() {
	if File_api_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_errors_proto_rawDesc), len(file_api_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_errors_proto_goTypes,
		DependencyIndexes: file_api_errors_proto_depIdxs,
		MessageInfos:      file_api_errors_proto_msgTypes,
	}.Build()
	File_api_errors_proto = out.File
	file_api_errors_proto_goTypes = nil
	file_api_errors_proto_depIdxs = nil
}
