// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: api/specification.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpecificationService_Execute_FullMethodName = "/products.SpecificationService/Execute"
)

// SpecificationServiceClient is the client API for SpecificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpecificationServiceClient interface {
	Execute(ctx context.Context, in *SpecificationRequest, opts ...grpc.CallOption) (*SpecificationResponse, error)
}

type specificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpecificationServiceClient(cc grpc.ClientConnInterface) SpecificationServiceClient {
	return &specificationServiceClient{cc}
}

func (c *specificationServiceClient) Execute(ctx context.Context, in *SpecificationRequest, opts ...grpc.CallOption) (*SpecificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpecificationResponse)
	err := c.cc.Invoke(ctx, SpecificationService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpecificationServiceServer is the server API for SpecificationService service.
// All implementations must embed UnimplementedSpecificationServiceServer
// for forward compatibility.
type SpecificationServiceServer interface {
	Execute(context.Context, *SpecificationRequest) (*SpecificationResponse, error)
	mustEmbedUnimplementedSpecificationServiceServer()
}

// UnimplementedSpecificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpecificationServiceServer struct{}

func (UnimplementedSpecificationServiceServer) Execute(context.Context, *SpecificationRequest) (*SpecificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedSpecificationServiceServer) mustEmbedUnimplementedSpecificationServiceServer() {}
func (UnimplementedSpecificationServiceServer) testEmbeddedByValue()                              {}

// UnsafeSpecificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpecificationServiceServer will
// result in compilation errors.
type UnsafeSpecificationServiceServer interface {
	mustEmbedUnimplementedSpecificationServiceServer()
}

func RegisterSpecificationServiceServer(s grpc.ServiceRegistrar, srv SpecificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedSpecificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpecificationService_ServiceDesc, srv)
}

func _SpecificationService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpecificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecificationServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecificationService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecificationServiceServer).Execute(ctx, req.(*SpecificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpecificationService_ServiceDesc is the grpc.ServiceDesc for SpecificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpecificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "products.SpecificationService",
	HandlerType: (*SpecificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _SpecificationService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/specification.proto",
}
