// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/specification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpecificationType int32

const (
	SpecificationType_DEFAULT               SpecificationType = 0
	SpecificationType_DIRECT_SPECIFICATION  SpecificationType = 1
	SpecificationType_REVERSE_SPECIFICATION SpecificationType = 2
)

// Enum value maps for SpecificationType.
var (
	SpecificationType_name = map[int32]string{
		0: "DEFAULT",
		1: "DIRECT_SPECIFICATION",
		2: "REVERSE_SPECIFICATION",
	}
	SpecificationType_value = map[string]int32{
		"DEFAULT":               0,
		"DIRECT_SPECIFICATION":  1,
		"REVERSE_SPECIFICATION": 2,
	}
)

func (x SpecificationType) Enum() *SpecificationType {
	p := new(SpecificationType)
	*p = x
	return p
}

func (x SpecificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpecificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_specification_proto_enumTypes[0].Descriptor()
}

func (SpecificationType) Type() protoreflect.EnumType {
	return &file_api_specification_proto_enumTypes[0]
}

func (x SpecificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type PickupStrategy int32

const (
	PickupStrategy_NEAREST  PickupStrategy = 0
	PickupStrategy_FARTHEST PickupStrategy = 1
)

// Enum value maps for PickupStrategy.
var (
	PickupStrategy_name = map[int32]string{
		0: "NEAREST",
		1: "FARTHEST",
	}
	PickupStrategy_value = map[string]int32{
		"NEAREST":  0,
		"FARTHEST": 1,
	}
)

func (x PickupStrategy) Enum() *PickupStrategy {
	p := new(PickupStrategy)
	*p = x
	return p
}

func (x PickupStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PickupStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_specification_proto_enumTypes[1].Descriptor()
}

func (PickupStrategy) Type() protoreflect.EnumType {
	return &file_api_specification_proto_enumTypes[1]
}

func (x PickupStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SpecificationLine struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Fnrec       *string                `protobuf:"bytes,1,opt,name=fnrec"`
	xxx_hidden_Integration *string                `protobuf:"bytes,2,opt,name=integration"`
	xxx_hidden_Quantity    int32                  `protobuf:"varint,3,opt,name=quantity"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SpecificationLine) Reset() {
	*x = SpecificationLine{}
	mi := &file_api_specification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecificationLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecificationLine) ProtoMessage() {}

func (x *SpecificationLine) ProtoReflect() protoreflect.Message {
	mi := &file_api_specification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SpecificationLine) GetFnrec() string {
	if x != nil {
		if x.xxx_hidden_Fnrec != nil {
			return *x.xxx_hidden_Fnrec
		}
		return ""
	}
	return ""
}

func (x *SpecificationLine) GetIntegration() string {
	if x != nil {
		if x.xxx_hidden_Integration != nil {
			return *x.xxx_hidden_Integration
		}
		return ""
	}
	return ""
}

func (x *SpecificationLine) GetQuantity() int32 {
	if x != nil {
		return x.xxx_hidden_Quantity
	}
	return 0
}

func (x *SpecificationLine) SetFnrec(v string) {
	x.xxx_hidden_Fnrec = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *SpecificationLine) SetIntegration(v string) {
	x.xxx_hidden_Integration = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *SpecificationLine) SetQuantity(v int32) {
	x.xxx_hidden_Quantity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *SpecificationLine) HasFnrec() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SpecificationLine) HasIntegration() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SpecificationLine) HasQuantity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SpecificationLine) ClearFnrec() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Fnrec = nil
}

func (x *SpecificationLine) ClearIntegration() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Integration = nil
}

func (x *SpecificationLine) ClearQuantity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Quantity = 0
}

type SpecificationLine_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Fnrec       *string
	Integration *string
	Quantity    *int32
}

func (b0 SpecificationLine_builder) Build() *SpecificationLine {
	m0 := &SpecificationLine{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Fnrec != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Fnrec = b.Fnrec
	}
	if b.Integration != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Integration = b.Integration
	}
	if b.Quantity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Quantity = *b.Quantity
	}
	return m0
}

type SpecificationRequest struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SpecificationLines *[]*SpecificationLine  `protobuf:"bytes,1,rep,name=specification_lines,json=specificationLines"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SpecificationRequest) Reset() {
	*x = SpecificationRequest{}
	mi := &file_api_specification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecificationRequest) ProtoMessage() {}

func (x *SpecificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_specification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SpecificationRequest) GetSpecificationLines() []*SpecificationLine {
	if x != nil {
		if x.xxx_hidden_SpecificationLines != nil {
			return *x.xxx_hidden_SpecificationLines
		}
	}
	return nil
}

func (x *SpecificationRequest) SetSpecificationLines(v []*SpecificationLine) {
	x.xxx_hidden_SpecificationLines = &v
}

type SpecificationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SpecificationLines []*SpecificationLine
}

func (b0 SpecificationRequest_builder) Build() *SpecificationRequest {
	m0 := &SpecificationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SpecificationLines = &b.SpecificationLines
	return m0
}

type Line struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Product     *Product               `protobuf:"bytes,1,opt,name=product"`
	xxx_hidden_Quantity    int32                  `protobuf:"varint,2,opt,name=quantity"`
	xxx_hidden_Strategy    PickupStrategy         `protobuf:"varint,3,opt,name=strategy,enum=products.PickupStrategy"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_api_specification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_api_specification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Line) GetProduct() *Product {
	if x != nil {
		return x.xxx_hidden_Product
	}
	return nil
}

func (x *Line) GetQuantity() int32 {
	if x != nil {
		return x.xxx_hidden_Quantity
	}
	return 0
}

func (x *Line) GetStrategy() PickupStrategy {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Strategy
		}
	}
	return PickupStrategy_NEAREST
}

func (x *Line) SetProduct(v *Product) {
	x.xxx_hidden_Product = v
}

func (x *Line) SetQuantity(v int32) {
	x.xxx_hidden_Quantity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Line) SetStrategy(v PickupStrategy) {
	x.xxx_hidden_Strategy = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Line) HasProduct() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Product != nil
}

func (x *Line) HasQuantity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Line) HasStrategy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Line) ClearProduct() {
	x.xxx_hidden_Product = nil
}

func (x *Line) ClearQuantity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Quantity = 0
}

func (x *Line) ClearStrategy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Strategy = PickupStrategy_NEAREST
}

type Line_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Product  *Product
	Quantity *int32
	Strategy *PickupStrategy
}

func (b0 Line_builder) Build() *Line {
	m0 := &Line{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Product = b.Product
	if b.Quantity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Quantity = *b.Quantity
	}
	if b.Strategy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Strategy = *b.Strategy
	}
	return m0
}

type Specification struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Product      *Line                  `protobuf:"bytes,1,opt,name=product"`
	xxx_hidden_Type         SpecificationType      `protobuf:"varint,2,opt,name=type,enum=products.SpecificationType"`
	xxx_hidden_ChildProduct *[]*Line               `protobuf:"bytes,3,rep,name=child_product,json=childProduct"`
	xxx_hidden_Strategy     PickupStrategy         `protobuf:"varint,4,opt,name=strategy,enum=products.PickupStrategy"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Specification) Reset() {
	*x = Specification{}
	mi := &file_api_specification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Specification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specification) ProtoMessage() {}

func (x *Specification) ProtoReflect() protoreflect.Message {
	mi := &file_api_specification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Specification) GetProduct() *Line {
	if x != nil {
		return x.xxx_hidden_Product
	}
	return nil
}

func (x *Specification) GetType() SpecificationType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return SpecificationType_DEFAULT
}

func (x *Specification) GetChildProduct() []*Line {
	if x != nil {
		if x.xxx_hidden_ChildProduct != nil {
			return *x.xxx_hidden_ChildProduct
		}
	}
	return nil
}

func (x *Specification) GetStrategy() PickupStrategy {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_Strategy
		}
	}
	return PickupStrategy_NEAREST
}

func (x *Specification) SetProduct(v *Line) {
	x.xxx_hidden_Product = v
}

func (x *Specification) SetType(v SpecificationType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Specification) SetChildProduct(v []*Line) {
	x.xxx_hidden_ChildProduct = &v
}

func (x *Specification) SetStrategy(v PickupStrategy) {
	x.xxx_hidden_Strategy = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Specification) HasProduct() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Product != nil
}

func (x *Specification) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Specification) HasStrategy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Specification) ClearProduct() {
	x.xxx_hidden_Product = nil
}

func (x *Specification) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = SpecificationType_DEFAULT
}

func (x *Specification) ClearStrategy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Strategy = PickupStrategy_NEAREST
}

type Specification_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Product      *Line
	Type         *SpecificationType
	ChildProduct []*Line
	Strategy     *PickupStrategy
}

func (b0 Specification_builder) Build() *Specification {
	m0 := &Specification{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Product = b.Product
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Type = *b.Type
	}
	x.xxx_hidden_ChildProduct = &b.ChildProduct
	if b.Strategy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Strategy = *b.Strategy
	}
	return m0
}

type SpecificationResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Specifications *[]*Specification      `protobuf:"bytes,1,rep,name=specifications"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SpecificationResponse) Reset() {
	*x = SpecificationResponse{}
	mi := &file_api_specification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecificationResponse) ProtoMessage() {}

func (x *SpecificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_specification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SpecificationResponse) GetSpecifications() []*Specification {
	if x != nil {
		if x.xxx_hidden_Specifications != nil {
			return *x.xxx_hidden_Specifications
		}
	}
	return nil
}

func (x *SpecificationResponse) SetSpecifications(v []*Specification) {
	x.xxx_hidden_Specifications = &v
}

type SpecificationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Specifications []*Specification
}

func (b0 SpecificationResponse_builder) Build() *SpecificationResponse {
	m0 := &SpecificationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Specifications = &b.Specifications
	return m0
}

var File_api_specification_proto protoreflect.FileDescriptor

const file_api_specification_proto_rawDesc = "" +
	"\n" +
	"\x17api/specification.proto\x12\bproducts\x1a!google/protobuf/go_features.proto\x1a\x11api/product.proto\"g\n" +
	"\x11SpecificationLine\x12\x14\n" +
	"\x05fnrec\x18\x01 \x01(\tR\x05fnrec\x12 \n" +
	"\vintegration\x18\x02 \x01(\tR\vintegration\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"d\n" +
	"\x14SpecificationRequest\x12L\n" +
	"\x13specification_lines\x18\x01 \x03(\v2\x1b.products.SpecificationLineR\x12specificationLines\"\x85\x01\n" +
	"\x04Line\x12+\n" +
	"\aproduct\x18\x01 \x01(\v2\x11.products.ProductR\aproduct\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x124\n" +
	"\bstrategy\x18\x03 \x01(\x0e2\x18.products.PickupStrategyR\bstrategy\"\xd5\x01\n" +
	"\rSpecification\x12(\n" +
	"\aproduct\x18\x01 \x01(\v2\x0e.products.LineR\aproduct\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.products.SpecificationTypeR\x04type\x123\n" +
	"\rchild_product\x18\x03 \x03(\v2\x0e.products.LineR\fchildProduct\x124\n" +
	"\bstrategy\x18\x04 \x01(\x0e2\x18.products.PickupStrategyR\bstrategy\"X\n" +
	"\x15SpecificationResponse\x12?\n" +
	"\x0especifications\x18\x01 \x03(\v2\x17.products.SpecificationR\x0especifications*U\n" +
	"\x11SpecificationType\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\x18\n" +
	"\x14DIRECT_SPECIFICATION\x10\x01\x12\x19\n" +
	"\x15REVERSE_SPECIFICATION\x10\x02*+\n" +
	"\x0ePickupStrategy\x12\v\n" +
	"\aNEAREST\x10\x00\x12\f\n" +
	"\bFARTHEST\x10\x012b\n" +
	"\x14SpecificationService\x12J\n" +
	"\aExecute\x12\x1e.products.SpecificationRequest\x1a\x1f.products.SpecificationResponseB\x10Z\x06/proto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_api_specification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_specification_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_specification_proto_goTypes = []any{
	(SpecificationType)(0),        // 0: products.SpecificationType
	(PickupStrategy)(0),           // 1: products.PickupStrategy
	(*SpecificationLine)(nil),     // 2: products.SpecificationLine
	(*SpecificationRequest)(nil),  // 3: products.SpecificationRequest
	(*Line)(nil),                  // 4: products.Line
	(*Specification)(nil),         // 5: products.Specification
	(*SpecificationResponse)(nil), // 6: products.SpecificationResponse
	(*Product)(nil),               // 7: products.Product
}
var file_api_specification_proto_depIdxs = []int32{
	2, // 0: products.SpecificationRequest.specification_lines:type_name -> products.SpecificationLine
	7, // 1: products.Line.product:type_name -> products.Product
	1, // 2: products.Line.strategy:type_name -> products.PickupStrategy
	4, // 3: products.Specification.product:type_name -> products.Line
	0, // 4: products.Specification.type:type_name -> products.SpecificationType
	4, // 5: products.Specification.child_product:type_name -> products.Line
	1, // 6: products.Specification.strategy:type_name -> products.PickupStrategy
	5, // 7: products.SpecificationResponse.specifications:type_name -> products.Specification
	3, // 8: products.SpecificationService.Execute:input_type -> products.SpecificationRequest
	6, // 9: products.SpecificationService.Execute:output_type -> products.SpecificationResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_specification_proto_init() }
func file_api_specification_proto_init() {
	if File_api_specification_proto != nil {
		return
	}
	file_api_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_specification_proto_rawDesc), len(file_api_specification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_specification_proto_goTypes,
		DependencyIndexes: file_api_specification_proto_depIdxs,
		EnumInfos:         file_api_specification_proto_enumTypes,
		MessageInfos:      file_api_specification_proto_msgTypes,
	}.Build()
	File_api_specification_proto = out.File
	file_api_specification_proto_goTypes = nil
	file_api_specification_proto_depIdxs = nil
}
