// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/warehouse.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WarehouseType int32

const (
	WarehouseType_UNRECOGNIZED              WarehouseType = 0
	WarehouseType_FREE                      WarehouseType = 1
	WarehouseType_MAIN                      WarehouseType = 2
	WarehouseType_CENTRAL                   WarehouseType = 3
	WarehouseType_MALL                      WarehouseType = 4
	WarehouseType_TRANSIT                   WarehouseType = 5
	WarehouseType_RESERVATION               WarehouseType = 6
	WarehouseType_LOSES                     WarehouseType = 7
	WarehouseType_MARKETING                 WarehouseType = 8
	WarehouseType_EXPOSITION                WarehouseType = 9
	WarehouseType_PARTNER                   WarehouseType = 10
	WarehouseType_PARTNER2                  WarehouseType = 11
	WarehouseType_FREE2                     WarehouseType = 12
	WarehouseType_PROBLEM                   WarehouseType = 13
	WarehouseType_REFUND                    WarehouseType = 14
	WarehouseType_PRODUCTION                WarehouseType = 15
	WarehouseType_RECYCLING                 WarehouseType = 16
	WarehouseType_SERVICE                   WarehouseType = 17
	WarehouseType_MATERIAL                  WarehouseType = 18
	WarehouseType_MARKDOWN                  WarehouseType = 19
	WarehouseType_BUFFER                    WarehouseType = 20
	WarehouseType_DISCOUNT                  WarehouseType = 21
	WarehouseType_CENTRAL_MAIN_INTERMEDIATE WarehouseType = 22
	WarehouseType_MAIN_CENTRAL_INTERMEDIATE WarehouseType = 23
	WarehouseType_CENTRAL_FREE_INTERMEDIATE WarehouseType = 24
	WarehouseType_FREE_CENTRAL_INTERMEDIATE WarehouseType = 25
)

// Enum value maps for WarehouseType.
var (
	WarehouseType_name = map[int32]string{
		0:  "UNRECOGNIZED",
		1:  "FREE",
		2:  "MAIN",
		3:  "CENTRAL",
		4:  "MALL",
		5:  "TRANSIT",
		6:  "RESERVATION",
		7:  "LOSES",
		8:  "MARKETING",
		9:  "EXPOSITION",
		10: "PARTNER",
		11: "PARTNER2",
		12: "FREE2",
		13: "PROBLEM",
		14: "REFUND",
		15: "PRODUCTION",
		16: "RECYCLING",
		17: "SERVICE",
		18: "MATERIAL",
		19: "MARKDOWN",
		20: "BUFFER",
		21: "DISCOUNT",
		22: "CENTRAL_MAIN_INTERMEDIATE",
		23: "MAIN_CENTRAL_INTERMEDIATE",
		24: "CENTRAL_FREE_INTERMEDIATE",
		25: "FREE_CENTRAL_INTERMEDIATE",
	}
	WarehouseType_value = map[string]int32{
		"UNRECOGNIZED":              0,
		"FREE":                      1,
		"MAIN":                      2,
		"CENTRAL":                   3,
		"MALL":                      4,
		"TRANSIT":                   5,
		"RESERVATION":               6,
		"LOSES":                     7,
		"MARKETING":                 8,
		"EXPOSITION":                9,
		"PARTNER":                   10,
		"PARTNER2":                  11,
		"FREE2":                     12,
		"PROBLEM":                   13,
		"REFUND":                    14,
		"PRODUCTION":                15,
		"RECYCLING":                 16,
		"SERVICE":                   17,
		"MATERIAL":                  18,
		"MARKDOWN":                  19,
		"BUFFER":                    20,
		"DISCOUNT":                  21,
		"CENTRAL_MAIN_INTERMEDIATE": 22,
		"MAIN_CENTRAL_INTERMEDIATE": 23,
		"CENTRAL_FREE_INTERMEDIATE": 24,
		"FREE_CENTRAL_INTERMEDIATE": 25,
	}
)

func (x WarehouseType) Enum() *WarehouseType {
	p := new(WarehouseType)
	*p = x
	return p
}

func (x WarehouseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WarehouseType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_warehouse_proto_enumTypes[0].Descriptor()
}

func (WarehouseType) Type() protoreflect.EnumType {
	return &file_api_warehouse_proto_enumTypes[0]
}

func (x WarehouseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Warehouse struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                     *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name                   *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Type                   WarehouseType          `protobuf:"varint,3,opt,name=type,enum=warehouses.WarehouseType"`
	xxx_hidden_TimeZone               *string                `protobuf:"bytes,4,opt,name=time_zone,json=timeZone"`
	xxx_hidden_AvailableRest          bool                   `protobuf:"varint,5,opt,name=available_rest,json=availableRest"`
	xxx_hidden_Level                  int32                  `protobuf:"varint,6,opt,name=level"`
	xxx_hidden_Address                *string                `protobuf:"bytes,7,opt,name=address"`
	xxx_hidden_OnlyStockPickupAllowed bool                   `protobuf:"varint,8,opt,name=only_stock_pickup_allowed,json=onlyStockPickupAllowed"`
	xxx_hidden_DescriptorGroup        *string                `protobuf:"bytes,9,opt,name=DescriptorGroup"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_api_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Warehouse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Warehouse) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Warehouse) GetType() WarehouseType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Type
		}
	}
	return WarehouseType_UNRECOGNIZED
}

func (x *Warehouse) GetTimeZone() string {
	if x != nil {
		if x.xxx_hidden_TimeZone != nil {
			return *x.xxx_hidden_TimeZone
		}
		return ""
	}
	return ""
}

func (x *Warehouse) GetAvailableRest() bool {
	if x != nil {
		return x.xxx_hidden_AvailableRest
	}
	return false
}

func (x *Warehouse) GetLevel() int32 {
	if x != nil {
		return x.xxx_hidden_Level
	}
	return 0
}

func (x *Warehouse) GetAddress() string {
	if x != nil {
		if x.xxx_hidden_Address != nil {
			return *x.xxx_hidden_Address
		}
		return ""
	}
	return ""
}

func (x *Warehouse) GetOnlyStockPickupAllowed() bool {
	if x != nil {
		return x.xxx_hidden_OnlyStockPickupAllowed
	}
	return false
}

func (x *Warehouse) GetDescriptorGroup() string {
	if x != nil {
		if x.xxx_hidden_DescriptorGroup != nil {
			return *x.xxx_hidden_DescriptorGroup
		}
		return ""
	}
	return ""
}

func (x *Warehouse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *Warehouse) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *Warehouse) SetType(v WarehouseType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *Warehouse) SetTimeZone(v string) {
	x.xxx_hidden_TimeZone = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *Warehouse) SetAvailableRest(v bool) {
	x.xxx_hidden_AvailableRest = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *Warehouse) SetLevel(v int32) {
	x.xxx_hidden_Level = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *Warehouse) SetAddress(v string) {
	x.xxx_hidden_Address = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *Warehouse) SetOnlyStockPickupAllowed(v bool) {
	x.xxx_hidden_OnlyStockPickupAllowed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *Warehouse) SetDescriptorGroup(v string) {
	x.xxx_hidden_DescriptorGroup = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *Warehouse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Warehouse) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Warehouse) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Warehouse) HasTimeZone() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Warehouse) HasAvailableRest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Warehouse) HasLevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Warehouse) HasAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Warehouse) HasOnlyStockPickupAllowed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Warehouse) HasDescriptorGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *Warehouse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Warehouse) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Warehouse) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Type = WarehouseType_UNRECOGNIZED
}

func (x *Warehouse) ClearTimeZone() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TimeZone = nil
}

func (x *Warehouse) ClearAvailableRest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_AvailableRest = false
}

func (x *Warehouse) ClearLevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Level = 0
}

func (x *Warehouse) ClearAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Address = nil
}

func (x *Warehouse) ClearOnlyStockPickupAllowed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_OnlyStockPickupAllowed = false
}

func (x *Warehouse) ClearDescriptorGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_DescriptorGroup = nil
}

type Warehouse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                     *string
	Name                   *string
	Type                   *WarehouseType
	TimeZone               *string
	AvailableRest          *bool
	Level                  *int32
	Address                *string
	OnlyStockPickupAllowed *bool
	DescriptorGroup        *string
}

func (b0 Warehouse_builder) Build() *Warehouse {
	m0 := &Warehouse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Name = b.Name
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Type = *b.Type
	}
	if b.TimeZone != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_TimeZone = b.TimeZone
	}
	if b.AvailableRest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_AvailableRest = *b.AvailableRest
	}
	if b.Level != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Level = *b.Level
	}
	if b.Address != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_Address = b.Address
	}
	if b.OnlyStockPickupAllowed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_OnlyStockPickupAllowed = *b.OnlyStockPickupAllowed
	}
	if b.DescriptorGroup != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_DescriptorGroup = b.DescriptorGroup
	}
	return m0
}

type Path struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes *[]*Warehouse          `protobuf:"bytes,1,rep,name=nodes"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_api_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Path) GetNodes() []*Warehouse {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *Path) SetNodes(v []*Warehouse) {
	x.xxx_hidden_Nodes = &v
}

type Path_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes []*Warehouse
}

func (b0 Path_builder) Build() *Path {
	m0 := &Path{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = &b.Nodes
	return m0
}

type GetPath struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                 *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_DefaultWarehouseId *string                `protobuf:"bytes,2,opt,name=default_warehouse_id,json=defaultWarehouseId"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *GetPath) Reset() {
	*x = GetPath{}
	mi := &file_api_warehouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPath) ProtoMessage() {}

func (x *GetPath) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetPath) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetPath) GetDefaultWarehouseId() string {
	if x != nil {
		if x.xxx_hidden_DefaultWarehouseId != nil {
			return *x.xxx_hidden_DefaultWarehouseId
		}
		return ""
	}
	return ""
}

func (x *GetPath) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *GetPath) SetDefaultWarehouseId(v string) {
	x.xxx_hidden_DefaultWarehouseId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GetPath) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetPath) HasDefaultWarehouseId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetPath) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *GetPath) ClearDefaultWarehouseId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DefaultWarehouseId = nil
}

type GetPath_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                 *string
	DefaultWarehouseId *string
}

func (b0 GetPath_builder) Build() *GetPath {
	m0 := &GetPath{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.DefaultWarehouseId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_DefaultWarehouseId = b.DefaultWarehouseId
	}
	return m0
}

type DeliveryPathRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Node *[]*Warehouse          `protobuf:"bytes,1,rep,name=node"`
	xxx_hidden_From *Warehouse             `protobuf:"bytes,2,opt,name=from"`
	xxx_hidden_To   *Warehouse             `protobuf:"bytes,3,opt,name=to"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeliveryPathRequest) Reset() {
	*x = DeliveryPathRequest{}
	mi := &file_api_warehouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryPathRequest) ProtoMessage() {}

func (x *DeliveryPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeliveryPathRequest) GetNode() []*Warehouse {
	if x != nil {
		if x.xxx_hidden_Node != nil {
			return *x.xxx_hidden_Node
		}
	}
	return nil
}

func (x *DeliveryPathRequest) GetFrom() *Warehouse {
	if x != nil {
		return x.xxx_hidden_From
	}
	return nil
}

func (x *DeliveryPathRequest) GetTo() *Warehouse {
	if x != nil {
		return x.xxx_hidden_To
	}
	return nil
}

func (x *DeliveryPathRequest) SetNode(v []*Warehouse) {
	x.xxx_hidden_Node = &v
}

func (x *DeliveryPathRequest) SetFrom(v *Warehouse) {
	x.xxx_hidden_From = v
}

func (x *DeliveryPathRequest) SetTo(v *Warehouse) {
	x.xxx_hidden_To = v
}

func (x *DeliveryPathRequest) HasFrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_From != nil
}

func (x *DeliveryPathRequest) HasTo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_To != nil
}

func (x *DeliveryPathRequest) ClearFrom() {
	x.xxx_hidden_From = nil
}

func (x *DeliveryPathRequest) ClearTo() {
	x.xxx_hidden_To = nil
}

type DeliveryPathRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Node []*Warehouse
	From *Warehouse
	To   *Warehouse
}

func (b0 DeliveryPathRequest_builder) Build() *DeliveryPathRequest {
	m0 := &DeliveryPathRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Node = &b.Node
	x.xxx_hidden_From = b.From
	x.xxx_hidden_To = b.To
	return m0
}

type DeliveryPath struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_First *Warehouse             `protobuf:"bytes,1,opt,name=first"`
	xxx_hidden_Last  *Warehouse             `protobuf:"bytes,2,opt,name=last"`
	xxx_hidden_Path  *Path                  `protobuf:"bytes,3,opt,name=path"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeliveryPath) Reset() {
	*x = DeliveryPath{}
	mi := &file_api_warehouse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryPath) ProtoMessage() {}

func (x *DeliveryPath) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeliveryPath) GetFirst() *Warehouse {
	if x != nil {
		return x.xxx_hidden_First
	}
	return nil
}

func (x *DeliveryPath) GetLast() *Warehouse {
	if x != nil {
		return x.xxx_hidden_Last
	}
	return nil
}

func (x *DeliveryPath) GetPath() *Path {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return nil
}

func (x *DeliveryPath) SetFirst(v *Warehouse) {
	x.xxx_hidden_First = v
}

func (x *DeliveryPath) SetLast(v *Warehouse) {
	x.xxx_hidden_Last = v
}

func (x *DeliveryPath) SetPath(v *Path) {
	x.xxx_hidden_Path = v
}

func (x *DeliveryPath) HasFirst() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_First != nil
}

func (x *DeliveryPath) HasLast() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Last != nil
}

func (x *DeliveryPath) HasPath() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Path != nil
}

func (x *DeliveryPath) ClearFirst() {
	x.xxx_hidden_First = nil
}

func (x *DeliveryPath) ClearLast() {
	x.xxx_hidden_Last = nil
}

func (x *DeliveryPath) ClearPath() {
	x.xxx_hidden_Path = nil
}

type DeliveryPath_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	First *Warehouse
	Last  *Warehouse
	Path  *Path
}

func (b0 DeliveryPath_builder) Build() *DeliveryPath {
	m0 := &DeliveryPath{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_First = b.First
	x.xxx_hidden_Last = b.Last
	x.xxx_hidden_Path = b.Path
	return m0
}

type DeliveryPathResult struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success      bool                   `protobuf:"varint,1,opt,name=success"`
	xxx_hidden_DeliveryPath *DeliveryPath          `protobuf:"bytes,2,opt,name=delivery_path,json=deliveryPath"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DeliveryPathResult) Reset() {
	*x = DeliveryPathResult{}
	mi := &file_api_warehouse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryPathResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryPathResult) ProtoMessage() {}

func (x *DeliveryPathResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeliveryPathResult) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *DeliveryPathResult) GetDeliveryPath() *DeliveryPath {
	if x != nil {
		return x.xxx_hidden_DeliveryPath
	}
	return nil
}

func (x *DeliveryPathResult) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DeliveryPathResult) SetDeliveryPath(v *DeliveryPath) {
	x.xxx_hidden_DeliveryPath = v
}

func (x *DeliveryPathResult) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeliveryPathResult) HasDeliveryPath() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeliveryPath != nil
}

func (x *DeliveryPathResult) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

func (x *DeliveryPathResult) ClearDeliveryPath() {
	x.xxx_hidden_DeliveryPath = nil
}

type DeliveryPathResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success      *bool
	DeliveryPath *DeliveryPath
}

func (b0 DeliveryPathResult_builder) Build() *DeliveryPathResult {
	m0 := &DeliveryPathResult{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Success = *b.Success
	}
	x.xxx_hidden_DeliveryPath = b.DeliveryPath
	return m0
}

var File_api_warehouse_proto protoreflect.FileDescriptor

const file_api_warehouse_proto_rawDesc = "" +
	"\n" +
	"\x13api/warehouse.proto\x12\n" +
	"warehouses\x1a!google/protobuf/go_features.proto\"\xb7\x02\n" +
	"\tWarehouse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.warehouses.WarehouseTypeR\x04type\x12\x1b\n" +
	"\ttime_zone\x18\x04 \x01(\tR\btimeZone\x12%\n" +
	"\x0eavailable_rest\x18\x05 \x01(\bR\ravailableRest\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x129\n" +
	"\x19only_stock_pickup_allowed\x18\b \x01(\bR\x16onlyStockPickupAllowed\x12(\n" +
	"\x0fDescriptorGroup\x18\t \x01(\tR\x0fDescriptorGroup\"3\n" +
	"\x04Path\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.warehouses.WarehouseR\x05nodes\"K\n" +
	"\aGetPath\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x14default_warehouse_id\x18\x02 \x01(\tR\x12defaultWarehouseId\"\x92\x01\n" +
	"\x13DeliveryPathRequest\x12)\n" +
	"\x04node\x18\x01 \x03(\v2\x15.warehouses.WarehouseR\x04node\x12)\n" +
	"\x04from\x18\x02 \x01(\v2\x15.warehouses.WarehouseR\x04from\x12%\n" +
	"\x02to\x18\x03 \x01(\v2\x15.warehouses.WarehouseR\x02to\"\x8c\x01\n" +
	"\fDeliveryPath\x12+\n" +
	"\x05first\x18\x01 \x01(\v2\x15.warehouses.WarehouseR\x05first\x12)\n" +
	"\x04last\x18\x02 \x01(\v2\x15.warehouses.WarehouseR\x04last\x12$\n" +
	"\x04path\x18\x03 \x01(\v2\x10.warehouses.PathR\x04path\"m\n" +
	"\x12DeliveryPathResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12=\n" +
	"\rdelivery_path\x18\x02 \x01(\v2\x18.warehouses.DeliveryPathR\fdeliveryPath*\xb1\x03\n" +
	"\rWarehouseType\x12\x10\n" +
	"\fUNRECOGNIZED\x10\x00\x12\b\n" +
	"\x04FREE\x10\x01\x12\b\n" +
	"\x04MAIN\x10\x02\x12\v\n" +
	"\aCENTRAL\x10\x03\x12\b\n" +
	"\x04MALL\x10\x04\x12\v\n" +
	"\aTRANSIT\x10\x05\x12\x0f\n" +
	"\vRESERVATION\x10\x06\x12\t\n" +
	"\x05LOSES\x10\a\x12\r\n" +
	"\tMARKETING\x10\b\x12\x0e\n" +
	"\n" +
	"EXPOSITION\x10\t\x12\v\n" +
	"\aPARTNER\x10\n" +
	"\x12\f\n" +
	"\bPARTNER2\x10\v\x12\t\n" +
	"\x05FREE2\x10\f\x12\v\n" +
	"\aPROBLEM\x10\r\x12\n" +
	"\n" +
	"\x06REFUND\x10\x0e\x12\x0e\n" +
	"\n" +
	"PRODUCTION\x10\x0f\x12\r\n" +
	"\tRECYCLING\x10\x10\x12\v\n" +
	"\aSERVICE\x10\x11\x12\f\n" +
	"\bMATERIAL\x10\x12\x12\f\n" +
	"\bMARKDOWN\x10\x13\x12\n" +
	"\n" +
	"\x06BUFFER\x10\x14\x12\f\n" +
	"\bDISCOUNT\x10\x15\x12\x1d\n" +
	"\x19CENTRAL_MAIN_INTERMEDIATE\x10\x16\x12\x1d\n" +
	"\x19MAIN_CENTRAL_INTERMEDIATE\x10\x17\x12\x1d\n" +
	"\x19CENTRAL_FREE_INTERMEDIATE\x10\x18\x12\x1d\n" +
	"\x19FREE_CENTRAL_INTERMEDIATE\x10\x192\x8f\x01\n" +
	"\vPathService\x12,\n" +
	"\x03Get\x12\x13.warehouses.GetPath\x1a\x10.warehouses.Path\x12R\n" +
	"\x0fGetDeliveryPath\x12\x1f.warehouses.DeliveryPathRequest\x1a\x1e.warehouses.DeliveryPathResultB\x10Z\x06/proto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_api_warehouse_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_warehouse_proto_goTypes = []any{
	(WarehouseType)(0),          // 0: warehouses.WarehouseType
	(*Warehouse)(nil),           // 1: warehouses.Warehouse
	(*Path)(nil),                // 2: warehouses.Path
	(*GetPath)(nil),             // 3: warehouses.GetPath
	(*DeliveryPathRequest)(nil), // 4: warehouses.DeliveryPathRequest
	(*DeliveryPath)(nil),        // 5: warehouses.DeliveryPath
	(*DeliveryPathResult)(nil),  // 6: warehouses.DeliveryPathResult
}
var file_api_warehouse_proto_depIdxs = []int32{
	0,  // 0: warehouses.Warehouse.type:type_name -> warehouses.WarehouseType
	1,  // 1: warehouses.Path.nodes:type_name -> warehouses.Warehouse
	1,  // 2: warehouses.DeliveryPathRequest.node:type_name -> warehouses.Warehouse
	1,  // 3: warehouses.DeliveryPathRequest.from:type_name -> warehouses.Warehouse
	1,  // 4: warehouses.DeliveryPathRequest.to:type_name -> warehouses.Warehouse
	1,  // 5: warehouses.DeliveryPath.first:type_name -> warehouses.Warehouse
	1,  // 6: warehouses.DeliveryPath.last:type_name -> warehouses.Warehouse
	2,  // 7: warehouses.DeliveryPath.path:type_name -> warehouses.Path
	5,  // 8: warehouses.DeliveryPathResult.delivery_path:type_name -> warehouses.DeliveryPath
	3,  // 9: warehouses.PathService.Get:input_type -> warehouses.GetPath
	4,  // 10: warehouses.PathService.GetDeliveryPath:input_type -> warehouses.DeliveryPathRequest
	2,  // 11: warehouses.PathService.Get:output_type -> warehouses.Path
	6,  // 12: warehouses.PathService.GetDeliveryPath:output_type -> warehouses.DeliveryPathResult
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_warehouse_proto_init() }
func file_api_warehouse_proto_init() {
	if File_api_warehouse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_warehouse_proto_rawDesc), len(file_api_warehouse_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_warehouse_proto_goTypes,
		DependencyIndexes: file_api_warehouse_proto_depIdxs,
		EnumInfos:         file_api_warehouse_proto_enumTypes,
		MessageInfos:      file_api_warehouse_proto_msgTypes,
	}.Build()
	File_api_warehouse_proto = out.File
	file_api_warehouse_proto_goTypes = nil
	file_api_warehouse_proto_depIdxs = nil
}
