// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/rests/v1/rests.proto

package restsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FilialId     *string                `protobuf:"bytes,1,opt,name=filial_id,json=filialId"`
	xxx_hidden_WarehouseIds []string               `protobuf:"bytes,2,rep,name=warehouse_ids,json=warehouseIds"`
	xxx_hidden_ProductIds   []string               `protobuf:"bytes,3,rep,name=product_ids,json=productIds"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RestRequest) Reset() {
	*x = RestRequest{}
	mi := &file_api_rests_v1_rests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestRequest) ProtoMessage() {}

func (x *RestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rests_v1_rests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestRequest) GetFilialId() string {
	if x != nil {
		if x.xxx_hidden_FilialId != nil {
			return *x.xxx_hidden_FilialId
		}
		return ""
	}
	return ""
}

func (x *RestRequest) GetWarehouseIds() []string {
	if x != nil {
		return x.xxx_hidden_WarehouseIds
	}
	return nil
}

func (x *RestRequest) GetProductIds() []string {
	if x != nil {
		return x.xxx_hidden_ProductIds
	}
	return nil
}

func (x *RestRequest) SetFilialId(v string) {
	x.xxx_hidden_FilialId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RestRequest) SetWarehouseIds(v []string) {
	x.xxx_hidden_WarehouseIds = v
}

func (x *RestRequest) SetProductIds(v []string) {
	x.xxx_hidden_ProductIds = v
}

func (x *RestRequest) HasFilialId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RestRequest) ClearFilialId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FilialId = nil
}

type RestRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FilialId     *string
	WarehouseIds []string
	ProductIds   []string
}

func (b0 RestRequest_builder) Build() *RestRequest {
	m0 := &RestRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FilialId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_FilialId = b.FilialId
	}
	x.xxx_hidden_WarehouseIds = b.WarehouseIds
	x.xxx_hidden_ProductIds = b.ProductIds
	return m0
}

type Rest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ProductId   *string                `protobuf:"bytes,1,opt,name=product_id,json=productId"`
	xxx_hidden_WarehouseId *string                `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId"`
	xxx_hidden_FilialId    *string                `protobuf:"bytes,3,opt,name=filial_id,json=filialId"`
	xxx_hidden_Quantity    float64                `protobuf:"fixed64,4,opt,name=quantity"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Rest) Reset() {
	*x = Rest{}
	mi := &file_api_rests_v1_rests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rest) ProtoMessage() {}

func (x *Rest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rests_v1_rests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Rest) GetProductId() string {
	if x != nil {
		if x.xxx_hidden_ProductId != nil {
			return *x.xxx_hidden_ProductId
		}
		return ""
	}
	return ""
}

func (x *Rest) GetWarehouseId() string {
	if x != nil {
		if x.xxx_hidden_WarehouseId != nil {
			return *x.xxx_hidden_WarehouseId
		}
		return ""
	}
	return ""
}

func (x *Rest) GetFilialId() string {
	if x != nil {
		if x.xxx_hidden_FilialId != nil {
			return *x.xxx_hidden_FilialId
		}
		return ""
	}
	return ""
}

func (x *Rest) GetQuantity() float64 {
	if x != nil {
		return x.xxx_hidden_Quantity
	}
	return 0
}

func (x *Rest) SetProductId(v string) {
	x.xxx_hidden_ProductId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Rest) SetWarehouseId(v string) {
	x.xxx_hidden_WarehouseId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Rest) SetFilialId(v string) {
	x.xxx_hidden_FilialId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Rest) SetQuantity(v float64) {
	x.xxx_hidden_Quantity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Rest) HasProductId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Rest) HasWarehouseId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Rest) HasFilialId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Rest) HasQuantity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Rest) ClearProductId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ProductId = nil
}

func (x *Rest) ClearWarehouseId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_WarehouseId = nil
}

func (x *Rest) ClearFilialId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_FilialId = nil
}

func (x *Rest) ClearQuantity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Quantity = 0
}

type Rest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ProductId   *string
	WarehouseId *string
	FilialId    *string
	Quantity    *float64
}

func (b0 Rest_builder) Build() *Rest {
	m0 := &Rest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ProductId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ProductId = b.ProductId
	}
	if b.WarehouseId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_WarehouseId = b.WarehouseId
	}
	if b.FilialId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_FilialId = b.FilialId
	}
	if b.Quantity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Quantity = *b.Quantity
	}
	return m0
}

type RestMap struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Rests map[string]*Rest       `protobuf:"bytes,1,rep,name=rests" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestMap) Reset() {
	*x = RestMap{}
	mi := &file_api_rests_v1_rests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestMap) ProtoMessage() {}

func (x *RestMap) ProtoReflect() protoreflect.Message {
	mi := &file_api_rests_v1_rests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestMap) GetRests() map[string]*Rest {
	if x != nil {
		return x.xxx_hidden_Rests
	}
	return nil
}

func (x *RestMap) SetRests(v map[string]*Rest) {
	x.xxx_hidden_Rests = v
}

type RestMap_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Rests map[string]*Rest
}

func (b0 RestMap_builder) Build() *RestMap {
	m0 := &RestMap{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Rests = b.Rests
	return m0
}

type RestResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BalanceMap map[string]*RestMap    `protobuf:"bytes,1,rep,name=balance_map,json=balanceMap" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RestResponse) Reset() {
	*x = RestResponse{}
	mi := &file_api_rests_v1_rests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestResponse) ProtoMessage() {}

func (x *RestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rests_v1_rests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestResponse) GetBalanceMap() map[string]*RestMap {
	if x != nil {
		return x.xxx_hidden_BalanceMap
	}
	return nil
}

func (x *RestResponse) SetBalanceMap(v map[string]*RestMap) {
	x.xxx_hidden_BalanceMap = v
}

type RestResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BalanceMap map[string]*RestMap
}

func (b0 RestResponse_builder) Build() *RestResponse {
	m0 := &RestResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BalanceMap = b.BalanceMap
	return m0
}

var File_api_rests_v1_rests_proto protoreflect.FileDescriptor

const file_api_rests_v1_rests_proto_rawDesc = "" +
	"\n" +
	"\x18api/rests/v1/rests.proto\x12\x05rests\x1a!google/protobuf/go_features.proto\"p\n" +
	"\vRestRequest\x12\x1b\n" +
	"\tfilial_id\x18\x01 \x01(\tR\bfilialId\x12#\n" +
	"\rwarehouse_ids\x18\x02 \x03(\tR\fwarehouseIds\x12\x1f\n" +
	"\vproduct_ids\x18\x03 \x03(\tR\n" +
	"productIds\"\x81\x01\n" +
	"\x04Rest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x1b\n" +
	"\tfilial_id\x18\x03 \x01(\tR\bfilialId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\"\x81\x01\n" +
	"\aRestMap\x12/\n" +
	"\x05rests\x18\x01 \x03(\v2\x19.rests.RestMap.RestsEntryR\x05rests\x1aE\n" +
	"\n" +
	"RestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.rests.RestR\x05value:\x028\x01\"\xa3\x01\n" +
	"\fRestResponse\x12D\n" +
	"\vbalance_map\x18\x01 \x03(\v2#.rests.RestResponse.BalanceMapEntryR\n" +
	"balanceMap\x1aM\n" +
	"\x0fBalanceMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.rests.RestMapR\x05value:\x028\x012=\n" +
	"\vRestService\x12.\n" +
	"\x03Get\x12\x12.rests.RestRequest\x1a\x13.rests.RestResponseB<Z2github.com/DimKa163/dalty/pkg/api/rests/v1;restsv1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_api_rests_v1_rests_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_rests_v1_rests_proto_goTypes = []any{
	(*RestRequest)(nil),  // 0: rests.RestRequest
	(*Rest)(nil),         // 1: rests.Rest
	(*RestMap)(nil),      // 2: rests.RestMap
	(*RestResponse)(nil), // 3: rests.RestResponse
	nil,                  // 4: rests.RestMap.RestsEntry
	nil,                  // 5: rests.RestResponse.BalanceMapEntry
}
var file_api_rests_v1_rests_proto_depIdxs = []int32{
	4, // 0: rests.RestMap.rests:type_name -> rests.RestMap.RestsEntry
	5, // 1: rests.RestResponse.balance_map:type_name -> rests.RestResponse.BalanceMapEntry
	1, // 2: rests.RestMap.RestsEntry.value:type_name -> rests.Rest
	2, // 3: rests.RestResponse.BalanceMapEntry.value:type_name -> rests.RestMap
	0, // 4: rests.RestService.Get:input_type -> rests.RestRequest
	3, // 5: rests.RestService.Get:output_type -> rests.RestResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_rests_v1_rests_proto_init() }
func file_api_rests_v1_rests_proto_init() {
	if File_api_rests_v1_rests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rests_v1_rests_proto_rawDesc), len(file_api_rests_v1_rests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rests_v1_rests_proto_goTypes,
		DependencyIndexes: file_api_rests_v1_rests_proto_depIdxs,
		MessageInfos:      file_api_rests_v1_rests_proto_msgTypes,
	}.Build()
	File_api_rests_v1_rests_proto = out.File
	file_api_rests_v1_rests_proto_goTypes = nil
	file_api_rests_v1_rests_proto_depIdxs = nil
}
