// Code generated by MockGen. DO NOT EDIT.
// Source: I:\Goland\dalty\internal\product\core\product.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	core "github.com/DimKa163/dalty/internal/product/core"
	gomock "github.com/golang/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// GetByFnrec mocks base method.
func (m *MockProductRepository) GetByFnrec(ctx context.Context, fnrec string) (*core.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFnrec", ctx, fnrec)
	ret0, _ := ret[0].(*core.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFnrec indicates an expected call of GetByFnrec.
func (mr *MockProductRepositoryMockRecorder) GetByFnrec(ctx, fnrec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFnrec", reflect.TypeOf((*MockProductRepository)(nil).GetByFnrec), ctx, fnrec)
}

// GetByID mocks base method.
func (m *MockProductRepository) GetByID(ctx context.Context, id string) (*core.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*core.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProductRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProductRepository)(nil).GetByID), ctx, id)
}

// GetByIntegrationID mocks base method.
func (m *MockProductRepository) GetByIntegrationID(ctx context.Context, integrationID string) (*core.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIntegrationID", ctx, integrationID)
	ret0, _ := ret[0].(*core.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIntegrationID indicates an expected call of GetByIntegrationID.
func (mr *MockProductRepositoryMockRecorder) GetByIntegrationID(ctx, integrationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIntegrationID", reflect.TypeOf((*MockProductRepository)(nil).GetByIntegrationID), ctx, integrationID)
}
