// Code generated by MockGen. DO NOT EDIT.
// Source: I:\Goland\dalty\internal\product\core\relation.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	core "github.com/DimKa163/dalty/internal/product/core"
	guid "github.com/beevik/guid"
	gomock "github.com/golang/mock/gomock"
)

// MockRelationRepository is a mock of RelationRepository interface.
type MockRelationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRelationRepositoryMockRecorder
}

// MockRelationRepositoryMockRecorder is the mock recorder for MockRelationRepository.
type MockRelationRepositoryMockRecorder struct {
	mock *MockRelationRepository
}

// NewMockRelationRepository creates a new mock instance.
func NewMockRelationRepository(ctrl *gomock.Controller) *MockRelationRepository {
	mock := &MockRelationRepository{ctrl: ctrl}
	mock.recorder = &MockRelationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelationRepository) EXPECT() *MockRelationRepositoryMockRecorder {
	return m.recorder
}

// GetByLeftFnrec mocks base method.
func (m *MockRelationRepository) GetByLeftFnrec(ctx context.Context, fnrec string) ([]*core.Relation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLeftFnrec", ctx, fnrec)
	ret0, _ := ret[0].([]*core.Relation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLeftFnrec indicates an expected call of GetByLeftFnrec.
func (mr *MockRelationRepositoryMockRecorder) GetByLeftFnrec(ctx, fnrec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLeftFnrec", reflect.TypeOf((*MockRelationRepository)(nil).GetByLeftFnrec), ctx, fnrec)
}

// GetByLeftID mocks base method.
func (m *MockRelationRepository) GetByLeftID(ctx context.Context, id guid.Guid) ([]*core.Relation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLeftID", ctx, id)
	ret0, _ := ret[0].([]*core.Relation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLeftID indicates an expected call of GetByLeftID.
func (mr *MockRelationRepositoryMockRecorder) GetByLeftID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLeftID", reflect.TypeOf((*MockRelationRepository)(nil).GetByLeftID), ctx, id)
}

// GetByLeftIntegrationID mocks base method.
func (m *MockRelationRepository) GetByLeftIntegrationID(ctx context.Context, integrationID string) ([]*core.Relation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLeftIntegrationID", ctx, integrationID)
	ret0, _ := ret[0].([]*core.Relation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLeftIntegrationID indicates an expected call of GetByLeftIntegrationID.
func (mr *MockRelationRepositoryMockRecorder) GetByLeftIntegrationID(ctx, integrationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLeftIntegrationID", reflect.TypeOf((*MockRelationRepository)(nil).GetByLeftIntegrationID), ctx, integrationID)
}

// GetByRightID mocks base method.
func (m *MockRelationRepository) GetByRightID(ctx context.Context, lid, rid guid.Guid) (*core.Relation, *core.Relation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRightID", ctx, lid, rid)
	ret0, _ := ret[0].(*core.Relation)
	ret1, _ := ret[1].(*core.Relation)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByRightID indicates an expected call of GetByRightID.
func (mr *MockRelationRepositoryMockRecorder) GetByRightID(ctx, lid, rid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRightID", reflect.TypeOf((*MockRelationRepository)(nil).GetByRightID), ctx, lid, rid)
}
